#!/usr/bin/env bash

INFILE="$1"
OUTFILE="$2"
ENCODER="$(which avconv || which ffmpeg)"

if [ $# -lt 2 ]; then
  echo "Run $0 inputvideo output.webm [additional arguments]"
  exit 1
fi

if [ -z "$ENCODER" ]; then
  echo avconv or ffmpeg not found, please apt-get install either program.
  exit 1
fi

shift 2

$ENCODER -i "$INFILE" -c:v libvpx-vp9 -b:v 2M -pass 1 -an -f webm "$@" /dev/null || exit $?
$ENCODER -i "$INFILE" -c:v libvpx-vp9 -b:v 2M -pass 2 -c:a libopus "$OUTFILE"
